#!/usr/bin/env sh

PROJECT_BASE_PATH=$(git rev-parse --show-toplevel)
LAST_COMMIT=$(git rev-parse HEAD)
GO_FILES_STAGED=$(git diff --name-only --cached | grep -c .go)
export LAST_COMMIT="$LAST_COMMIT"

cd "$PROJECT_BASE_PATH" || exit 0

echo "[pre-commit] $PKG_RUNNER lint-staged"
npx -y lint-staged -v

if [ -n "$GO_FILES_STAGED" ] && [ "$GO_FILES_STAGED" != "0" ]; then
    echo "[pre-commit] running golangci-lint"

    GOLINT_BIN=$(which golangci-lint)

    if [ -n "$GOLINT_BIN" ]; then
        LAST_COMMIT=$(git rev-parse HEAD)

        echo "[pre-commit] $GOLINT_BIN run -c ./.golangci.yaml --new-from-rev $LAST_COMMIT"

        $GOLINT_BIN run -c ./.golangci.yaml --new-from-rev "$LAST_COMMIT"
    fi
else
    echo "[pre-commit] skipping golangci-lint, no go files staged"
fi