default: true
extends: null

first-line-heading: false

no-hard-tabs: true
no-inline-html: false
no-trailing-spaces: false

header-style:
  style: atx

line-length:
  heading_line_length: 120
  line_length: 160
  code_blocks: false
  tables: false

ul-indent:
  indent: 4

list-marker-space:
  ul_single: 1
  ul_multi: 1

MD013: false # line length
MD033: false # inline HTML
MD034: false # bare URLs