name: lint-code
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, reopened, ready_for_review]
  pull_request_target:
    types: [opened, edited, reopened, ready_for_review]

env:
  GO_VERSION: "~1.22"
  GO111MODULE: "on"

permissions:
  # Required: allow read access to the content for analysis.
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
  # Optional: Allow write access to checks to allow the action to annotate code in the PR.
  checks: write

jobs:
  run-golangci-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Lint project code
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m --out-format=github-actions
          skip-save-cache: false

